test_that("split mode creates ai_project and r_project with mirrored data route", {
  path <- tempfile("airsetup-")
  create_agentic_project(path, mode = "split")

  expect_true(dir.exists(file.path(path, "ai_project")))
  expect_true(dir.exists(file.path(path, "r_project")))
  expect_true(dir.exists(file.path(path, "ai_project", "01_study_documentation_package", "source")))
  expect_false(dir.exists(file.path(path, "01_study_documentation_package")))
  expect_true(file.exists(file.path(path, "ai_project", "AGENTS.md")))
  expect_true(dir.exists(file.path(path, "ai_project", "ai_visible_data", "input")))
  expect_true(file.exists(file.path(path, "ai_project", "ai_visible_data", "metadata", "data_contract.md")))
  expect_true(file.exists(file.path(path, "ai_project", "ai_visible_data", "metadata", "data_manifest.csv")))
  expect_true(dir.exists(file.path(path, "r_project", "ai_hidden_data", "input")))
  expect_true(file.exists(file.path(path, "ai_project", "04_ai_context_package", "active", "active_task.md")))
  expect_true(file.exists(file.path(path, "ai_project", "04_ai_context_package", "active", "execution_contract.md")))
  expect_true(file.exists(file.path(path, "ai_project", "04_ai_context_package", "active", "data_contract.md")))
  expect_false(dir.exists(file.path(path, "ai_project", "06_analysis_execution", "datasets", "dummy")))
})

test_that("ai_only mode creates ai_project but not r_project", {
  path <- tempfile("airsetup-")
  create_agentic_project(path, mode = "ai_only")

  expect_true(dir.exists(file.path(path, "ai_project")))
  expect_false(dir.exists(file.path(path, "r_project")))
  expect_true(dir.exists(file.path(path, "ai_project", "ai_visible_data", "input")))
  expect_true(file.exists(file.path(path, "ai_project", "ai_visible_data", "metadata", "data_contract.md")))
  expect_true(file.exists(file.path(path, "ai_project", "ai_visible_data", "metadata", "data_manifest.csv")))
  expect_false(dir.exists(file.path(path, "06_analysis_execution")))
})

test_that("overwrite behavior preserves existing files by default", {
  path <- tempfile("airsetup-")
  create_agentic_project(path, mode = "ai_only")
  agents <- file.path(path, "ai_project", "AGENTS.md")
  writeLines("custom", agents)
  create_agentic_project(path, mode = "ai_only", overwrite = FALSE)
  expect_equal(readLines(agents), "custom")
  create_agentic_project(path, mode = "ai_only", overwrite = TRUE)
  expect_true(any(grepl("Checkpoint QC", readLines(agents))))
})

test_that("AGENTS.md includes simple AI workflow and data boundary rules", {
  path <- tempfile("airsetup-")
  create_agentic_project(path, mode = "ai_only")
  text <- paste(readLines(file.path(path, "ai_project", "AGENTS.md")), collapse = "\n")
  expect_match(text, "Default Codex workflow")
  expect_match(text, "Mirrored data layout contract")
  expect_match(text, "ai_visible_data")
  expect_match(text, "ai_hidden_data")
  expect_match(text, "data_dir")
  expect_match(text, "do not assume that the current working directory is `ai_project`", ignore.case = TRUE)
  expect_match(text, "Preflight")
  expect_match(text, "Flight")
  expect_match(text, "Landing")
  expect_match(text, "human_checkpoint")
  expect_match(text, "ai_assisted_human_checkpoint")
  expect_match(text, "automated_checkpoint")
  expect_match(text, "Software Inventory")
})

test_that("split mode r_project scaffold is minimal and protects hidden data", {
  path <- tempfile("airsetup-")
  create_agentic_project(path, mode = "split")

  gitignore <- file.path(path, "r_project", ".gitignore")
  expect_true(file.exists(gitignore))
  expect_true(any(readLines(gitignore) == "ai_hidden_data/"))
  expect_true(file.exists(file.path(path, "r_project", "ai_hidden_data", "README_DO_NOT_COMMIT.md")))
  expect_true(file.exists(file.path(path, "r_project", "programs", "run_analysis_template.R")))
  expect_false(dir.exists(file.path(path, "r_project", "data")))
  expect_false(dir.exists(file.path(path, "r_project", "config")))
  expect_false(dir.exists(file.path(path, "r_project", "outputs")))

  template <- paste(readLines(file.path(path, "r_project", "programs", "run_analysis_template.R")), collapse = "\n")
  expect_match(template, "ai_project_dir")
  expect_match(template, "data_dir")
  expect_match(template, "ai_hidden_data")
  expect_match(template, "output_dir")
  expect_match(template, "qc_dir")
})

test_that("checkpoint template contains phases and opener types", {
  path <- tempfile("airsetup-")
  create_agentic_project(path)
  cp <- read.csv(file.path(path, "ai_project", "05_qc_package", "template", "checkpoint_definition_template.csv"))
  expect_equal(cp$phase, c("Preflight", "Preflight", "Flight", "Flight", "Landing", "Landing"))
  expect_equal(cp$checkpoint_id, sprintf("C%02d", 1:6))
  expect_equal(cp$opener_type, c("human_checkpoint", "human_checkpoint", "ai_assisted_human_checkpoint", "human_checkpoint", "ai_assisted_human_checkpoint", "human_checkpoint"))
  expect_true(all(c("phase", "checkpoint_id", "checkpoint_name", "objective", "required_inputs", "expected_outputs", "check_items", "checkpoint_condition", "opener_type", "checkpoint_opener", "reviewer", "approval_required", "downstream_steps") %in% names(cp)))
})

test_that("software inventory template has required columns and status guidance", {
  path <- tempfile("airsetup-")
  create_agentic_project(path)
  inv <- read.csv(file.path(path, "ai_project", "03_statistical_analysis_package", "template", "software_inventory_template.csv"), check.names = FALSE)
  expect_true(all(c("category", "task", "package", "function", "status", "allowed_use", "restricted_use", "qc_requirement", "notes") %in% names(inv)))
  expect_match(inv$notes[1], "approved")
  expect_match(inv$notes[1], "under_review")
})

test_that("checkpoint QC templates have required columns", {
  path <- tempfile("airsetup-")
  create_agentic_project(path)
  checklist <- read.csv(file.path(path, "ai_project", "05_qc_package", "template", "checkpoint_checklist_template.csv"))
  decision <- read.csv(file.path(path, "ai_project", "05_qc_package", "template", "checkpoint_decision_log_template.csv"))
  discrepancy <- read.csv(file.path(path, "ai_project", "05_qc_package", "template", "checkpoint_discrepancy_log_template.csv"))
  expect_true(all(c("phase", "checkpoint_id", "check_item_id", "check_item_name", "description", "check_type", "expected_evidence", "result", "reviewer", "review_date", "comment") %in% names(checklist)))
  expect_true(all(c("phase", "checkpoint_id", "checkpoint_name", "opener_type", "checkpoint_decision", "decision_date", "decided_by", "evidence_reviewed", "unresolved_issues", "downstream_steps_allowed", "comment") %in% names(decision)))
  expect_true(all(c("discrepancy_id", "phase", "checkpoint_id", "detected_at", "description", "severity", "affected_files", "affected_downstream_steps", "resolution", "resolved_by", "resolved_at", "comment") %in% names(discrepancy)))
})

test_that("check_agentic_project reports all required split-mode items after creation", {
  path <- tempfile("airsetup-")
  dir.create(path)
  report <- check_agentic_project(path, mode = "split")
  expect_s3_class(report, "data.frame")
  expect_true(all(c("item", "type", "path", "exists", "required", "message") %in% names(report)))
  expect_true(any(!report$exists))
  create_agentic_project(path, mode = "split")
  report2 <- check_agentic_project(path, mode = "split")
  expect_true(all(report2$exists))
  expect_true("ai_project/ai_visible_data/input" %in% report2$item)
  expect_true("r_project/ai_hidden_data/input" %in% report2$item)
  expect_true("r_project/programs/run_analysis_template.R" %in% report2$item)
  expect_false("r_project/data" %in% report2$item)
  expect_false("r_project/config" %in% report2$item)
  expect_false("r_project/outputs" %in% report2$item)
})

test_that("check_agentic_project reports all required ai-only items after creation", {
  path <- tempfile("airsetup-")
  create_agentic_project(path, mode = "ai_only")
  report <- check_agentic_project(path, mode = "ai_only")
  expect_true(all(report$exists))
  expect_true(all(grepl("^ai_project/", report$path)))
  expect_true("ai_project/04_ai_context_package/active/active_task.md" %in% report$item)
  expect_true("ai_project/ai_visible_data/metadata/data_manifest.csv" %in% report$item)
})
