test_that("split mode creates ai_project and r_project with minimal data route", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "split")

  expect_true(dir.exists(file.path(path, "ai_project")))
  expect_true(dir.exists(file.path(path, "r_project")))

  expected_ai_dirs <- file.path(
    path,
    "ai_project",
    c(
      "source",
      "source/initial",
      "ai_visible_data",
      "ai_visible_data/initial",
      "ai_output",
      "r_output",
      "qc",
      "log"
    )
  )
  expect_true(all(dir.exists(expected_ai_dirs)))

  expect_true(file.exists(file.path(path, "ai_project", "AGENTS.md")))
  expect_true(file.exists(file.path(path, "ai_project", "QC_STATUS.md")))

  expect_true(dir.exists(file.path(path, "r_project", "ai_hidden_data")))
  expect_true(dir.exists(file.path(path, "r_project", "ai_hidden_data", "initial")))
  expect_true(file.exists(file.path(path, "r_project", ".gitignore")))
  expect_true(file.exists(file.path(path, "r_project", "README_DO_NOT_SHARE_WITH_AI.md")))

  expect_false(dir.exists(file.path(path, "ai_project", "01_study_documentation_package")))
  expect_false(dir.exists(file.path(path, "ai_project", "04_ai_context_package")))
  expect_false(dir.exists(file.path(path, "ai_project", "05_qc_package")))
  expect_false(dir.exists(file.path(path, "ai_project", "06_analysis_execution")))
  expect_false(dir.exists(file.path(path, "r_project", "data")))
  expect_false(dir.exists(file.path(path, "r_project", "programs")))
  expect_false(dir.exists(file.path(path, "r_project", "outputs")))
})

test_that("ai_only mode creates ai_project but not r_project", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "ai_only")

  expect_true(dir.exists(file.path(path, "ai_project")))
  expect_false(dir.exists(file.path(path, "r_project")))

  expect_true(dir.exists(file.path(path, "ai_project", "source", "initial")))
  expect_true(dir.exists(file.path(path, "ai_project", "ai_visible_data", "initial")))
  expect_true(dir.exists(file.path(path, "ai_project", "ai_output")))
  expect_true(dir.exists(file.path(path, "ai_project", "r_output")))
  expect_true(dir.exists(file.path(path, "ai_project", "qc")))
  expect_true(dir.exists(file.path(path, "ai_project", "log")))

  expect_true(file.exists(file.path(path, "ai_project", "AGENTS.md")))
  expect_true(file.exists(file.path(path, "ai_project", "QC_STATUS.md")))
})

test_that("overwrite behavior preserves existing files by default", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "ai_only")

  agents <- file.path(path, "ai_project", "AGENTS.md")
  qc_status <- file.path(path, "ai_project", "QC_STATUS.md")

  writeLines("custom agents", agents)
  writeLines("custom qc", qc_status)

  airsetup(path, mode = "ai_only", overwrite = FALSE)
  expect_equal(readLines(agents, warn = FALSE), "custom agents")
  expect_equal(readLines(qc_status, warn = FALSE), "custom qc")

  airsetup(path, mode = "ai_only", japanese = TRUE, overwrite = TRUE)
  expect_identical(readLines(agents, warn = FALSE), agents_md_template(japanese = TRUE))
  expect_identical(readLines(qc_status, warn = FALSE), qc_status_template())
})

test_that("AGENTS.md is generated from the canonical English minimal template by default", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "ai_only")

  agents <- readLines(file.path(path, "ai_project", "AGENTS.md"), warn = FALSE)
  text <- paste(agents, collapse = "\n")

  expect_identical(agents, agents_md_template(japanese = FALSE))
  expect_match(text, "## Project Map", fixed = TRUE)
  expect_match(text, "`source/`", fixed = TRUE)
  expect_match(text, "`ai_visible_data/`", fixed = TRUE)
  expect_match(text, "`../r_project/ai_hidden_data/`", fixed = TRUE)
  expect_match(text, "`ai_output/`", fixed = TRUE)
  expect_match(text, "`r_output/`", fixed = TRUE)
  expect_match(text, "`qc/`", fixed = TRUE)
  expect_match(text, "`log/`", fixed = TRUE)
  expect_match(text, "`QC_STATUS.md`", fixed = TRUE)
  expect_match(text, "Codex must not list, open, copy, move, summarize", fixed = TRUE)
  expect_match(text, "## Human Approval", fixed = TRUE)
  expect_match(text, "## Output Language", fixed = TRUE)
  expect_match(text, "generated by Codex should be written in English", fixed = TRUE)
  expect_false(grepl("generated by Codex should be written in Japanese", text, fixed = TRUE))
  expect_false(grepl("Checkpoint QC", text, fixed = TRUE))
  expect_false(grepl("Software Inventory", text, fixed = TRUE))
})

test_that("AGENTS.md records Japanese narrative output language when requested", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "ai_only", japanese = TRUE)

  agents <- readLines(file.path(path, "ai_project", "AGENTS.md"), warn = FALSE)
  text <- paste(agents, collapse = "\n")

  expect_identical(agents, agents_md_template(japanese = TRUE))
  expect_match(text, "## Output Language", fixed = TRUE)
  expect_match(text, "generated by Codex should be written in Japanese", fixed = TRUE)
  expect_match(text, "R scripts, source code, machine-readable tables", fixed = TRUE)
  expect_false(grepl("generated by Codex should be written in English", text, fixed = TRUE))
})

test_that("japanese must be a single TRUE or FALSE value", {
  path <- tempfile("airsetup-")

  expect_error(airsetup(path, japanese = NA), "japanese.*TRUE or FALSE")
  expect_error(airsetup(path, japanese = c(TRUE, FALSE)), "japanese.*TRUE or FALSE")
  expect_error(create_agents_md(path, japanese = "yes"), "japanese.*TRUE or FALSE")
})

test_that("QC_STATUS.md is generated as a minimal root status file", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "ai_only")

  qc_status <- readLines(file.path(path, "ai_project", "QC_STATUS.md"), warn = FALSE)

  expect_identical(qc_status, qc_status_template())
  expect_equal(qc_status[1], "# QC_STATUS.md")
  expect_true(any(grepl("No QC items have been registered yet.", qc_status, fixed = TRUE)))
})

test_that("split mode r_project scaffold is minimal and protects hidden data", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "split")

  gitignore <- file.path(path, "r_project", ".gitignore")
  readme <- file.path(path, "r_project", "README_DO_NOT_SHARE_WITH_AI.md")

  expect_true(file.exists(gitignore))
  expect_true(any(readLines(gitignore, warn = FALSE) == "ai_hidden_data/"))

  expect_true(file.exists(readme))
  readme_text <- paste(readLines(readme, warn = FALSE), collapse = "\n")
  expect_match(readme_text, "Do not share this folder with AI", fixed = TRUE)
  expect_match(readme_text, "ai_hidden_data/", fixed = TRUE)
  expect_match(readme_text, "../ai_project/ai_output/", fixed = TRUE)
  expect_match(readme_text, "../ai_project/r_output/", fixed = TRUE)

  expect_true(dir.exists(file.path(path, "r_project", "ai_hidden_data")))
  expect_true(dir.exists(file.path(path, "r_project", "ai_hidden_data", "initial")))
  expect_false(dir.exists(file.path(path, "r_project", "data")))
  expect_false(dir.exists(file.path(path, "r_project", "programs")))
  expect_false(dir.exists(file.path(path, "r_project", "config")))
  expect_false(dir.exists(file.path(path, "r_project", "outputs")))
})

test_that("check_agentic_project reports missing and found split-mode items", {
  path <- tempfile("airsetup-")
  dir.create(path)

  report <- check_agentic_project(path, mode = "split")
  expect_s3_class(report, "data.frame")
  expect_true(all(c("item", "type", "path", "exists", "required", "message") %in% names(report)))
  expect_true(any(!report$exists))

  airsetup(path, mode = "split")
  report2 <- check_agentic_project(path, mode = "split")

  expect_true(all(report2$exists))
  expect_true("ai_project/source/initial" %in% report2$item)
  expect_true("ai_project/ai_visible_data/initial" %in% report2$item)
  expect_true("ai_project/ai_output" %in% report2$item)
  expect_true("ai_project/r_output" %in% report2$item)
  expect_true("ai_project/qc" %in% report2$item)
  expect_true("ai_project/log" %in% report2$item)
  expect_true("ai_project/AGENTS.md" %in% report2$item)
  expect_true("ai_project/QC_STATUS.md" %in% report2$item)
  expect_true("r_project/ai_hidden_data/initial" %in% report2$item)

  expect_false("ai_project/04_ai_context_package/active/active_task.md" %in% report2$item)
  expect_false("ai_project/05_qc_package/template/checkpoint_definition_template.csv" %in% report2$item)
  expect_false("r_project/programs/run_analysis_template.R" %in% report2$item)
})

test_that("check_agentic_project reports all required ai-only items after creation", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "ai_only")

  report <- check_agentic_project(path, mode = "ai_only")

  expect_true(all(report$exists))
  expect_true(all(grepl("^ai_project/", report$path)))
  expect_false(any(grepl("^r_project/", report$path)))
  expect_true("ai_project/source/initial" %in% report$item)
  expect_true("ai_project/ai_visible_data/initial" %in% report$item)
  expect_true("ai_project/AGENTS.md" %in% report$item)
  expect_true("ai_project/QC_STATUS.md" %in% report$item)
})
