expect_one_dated_initial_dir <- function(parent) {
  dirs <- list.dirs(parent, full.names = FALSE, recursive = FALSE)
  matched <- dirs[grepl("^initial_[0-9]{8}$", dirs)]

  expect_length(matched, 1L)
  expect_true(dir.exists(file.path(parent, matched)))

  invisible(matched)
}

test_that("split mode creates ai_project and r_project with minimal data route", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "split")

  expect_true(dir.exists(file.path(path, "ai_project")))
  expect_true(dir.exists(file.path(path, "r_project")))

  expected_ai_dirs <- file.path(
    path,
    "ai_project",
    c(
      "source",
      "ai_visible_data",
      "ai_output",
      "r_output",
      "qc",
      "log"
    )
  )
  expect_true(all(dir.exists(expected_ai_dirs)))

  expect_one_dated_initial_dir(file.path(path, "ai_project", "source"))
  expect_one_dated_initial_dir(file.path(path, "ai_project", "ai_visible_data"))

  expect_true(file.exists(file.path(path, "ai_project", "AGENTS.md")))
  expect_true(file.exists(file.path(path, "ai_project", "QC_STATUS.md")))

  expect_true(dir.exists(file.path(path, "r_project", "ai_hidden_data")))
  expect_one_dated_initial_dir(file.path(path, "r_project", "ai_hidden_data"))
  expect_true(file.exists(file.path(path, "r_project", ".gitignore")))
  expect_true(file.exists(file.path(path, "r_project", "README_DO_NOT_SHARE_WITH_AI.md")))

  expect_false(dir.exists(file.path(path, "ai_project", "source", "initial")))
  expect_false(dir.exists(file.path(path, "ai_project", "ai_visible_data", "initial")))
  expect_false(dir.exists(file.path(path, "r_project", "ai_hidden_data", "initial")))

  expect_false(dir.exists(file.path(path, "ai_project", "01_study_documentation_package")))
  expect_false(dir.exists(file.path(path, "ai_project", "04_ai_context_package")))
  expect_false(dir.exists(file.path(path, "ai_project", "05_qc_package")))
  expect_false(dir.exists(file.path(path, "ai_project", "06_analysis_execution")))
  expect_false(dir.exists(file.path(path, "r_project", "data")))
  expect_false(dir.exists(file.path(path, "r_project", "programs")))
  expect_false(dir.exists(file.path(path, "r_project", "outputs")))
})

test_that("ai_only mode creates ai_project but not r_project", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "ai_only")

  expect_true(dir.exists(file.path(path, "ai_project")))
  expect_false(dir.exists(file.path(path, "r_project")))

  expect_true(dir.exists(file.path(path, "ai_project", "source")))
  expect_true(dir.exists(file.path(path, "ai_project", "ai_visible_data")))
  expect_one_dated_initial_dir(file.path(path, "ai_project", "source"))
  expect_one_dated_initial_dir(file.path(path, "ai_project", "ai_visible_data"))

  expect_true(dir.exists(file.path(path, "ai_project", "ai_output")))
  expect_true(dir.exists(file.path(path, "ai_project", "r_output")))
  expect_true(dir.exists(file.path(path, "ai_project", "qc")))
  expect_true(dir.exists(file.path(path, "ai_project", "log")))

  expect_false(dir.exists(file.path(path, "ai_project", "source", "initial")))
  expect_false(dir.exists(file.path(path, "ai_project", "ai_visible_data", "initial")))

  expect_true(file.exists(file.path(path, "ai_project", "AGENTS.md")))
  expect_true(file.exists(file.path(path, "ai_project", "QC_STATUS.md")))
})

test_that("airsetup_demo creates project, skills, and bundled demo materials", {
  path <- tempfile("airsetup-demo-")
  report <- airsetup_demo(path)

  expect_s3_class(report, "data.frame")
  expect_true(all(c("file", "path", "status", "overwritten") %in% names(report)))
  expect_true(any(report$file == "QC_SKILL_CONTEXT.md"))
  expect_true(any(report$file == "demodata.rds"))
  expect_true(any(report$file == "data_definition_demodata.txt"))

  initial <- initial_dir_name()
  visible_data <- file.path(path, "ai_project", "ai_visible_data", initial, "demodata.rds")
  hidden_data <- file.path(path, "r_project", "ai_hidden_data", initial, "demodata.rds")
  definition <- file.path(path, "ai_project", "source", initial, "data_definition_demodata.txt")

  expect_true(file.exists(visible_data))
  expect_true(file.exists(hidden_data))
  expect_true(file.exists(definition))

  expect_equal(nrow(readRDS(visible_data)), 3L)
  expect_equal(nrow(readRDS(hidden_data)), 502L)

  definition_text <- paste(readLines(definition, warn = FALSE), collapse = "\n")
  expect_match(definition_text, "prostate cancer trial", fixed = TRUE)
  expect_match(definition_text, "dtime", fixed = TRUE)
  expect_match(definition_text, "status", fixed = TRUE)

  agents <- paste(readLines(file.path(path, "ai_project", "AGENTS.md"), warn = FALSE), collapse = "\n")
  expect_match(agents, "generated by Codex should be written in Japanese", fixed = TRUE)
})

test_that("airsetup_demo can skip skills and preserves demo materials by default", {
  path <- tempfile("airsetup-demo-")
  airsetup_demo(path, skills = FALSE)

  initial <- initial_dir_name()
  visible_data <- file.path(path, "ai_project", "ai_visible_data", initial, "demodata.rds")
  saveRDS(data.frame(custom = 1), visible_data)

  report <- airsetup_demo(path, skills = FALSE, overwrite = FALSE)

  expect_false(any(report$file == "QC_SKILL_CONTEXT.md"))
  expect_true(any(report$path == file.path("ai_project", "ai_visible_data", initial, "demodata.rds") & report$status == "skipped"))
  expect_equal(names(readRDS(visible_data)), "custom")

  overwritten <- airsetup_demo(path, skills = FALSE, overwrite = TRUE)
  expect_true(any(overwritten$path == file.path("ai_project", "ai_visible_data", initial, "demodata.rds") & overwritten$status == "overwritten"))
  expect_equal(nrow(readRDS(visible_data)), 3L)
})

test_that("overwrite behavior preserves existing files by default", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "ai_only")

  agents <- file.path(path, "ai_project", "AGENTS.md")
  qc_status <- file.path(path, "ai_project", "QC_STATUS.md")

  writeLines("custom agents", agents)
  writeLines("custom qc", qc_status)

  airsetup(path, mode = "ai_only", overwrite = FALSE)
  expect_equal(readLines(agents, warn = FALSE), "custom agents")
  expect_equal(readLines(qc_status, warn = FALSE), "custom qc")

  airsetup(path, mode = "ai_only", japanese = TRUE, overwrite = TRUE)
  expect_identical(readLines(agents, warn = FALSE), agents_md_template(japanese = TRUE))
  expect_identical(readLines(qc_status, warn = FALSE), qc_status_template())
})

test_that("AGENTS.md is generated from the canonical English template by default", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "ai_only")

  agents <- readLines(file.path(path, "ai_project", "AGENTS.md"), warn = FALSE)
  text <- paste(agents, collapse = "\n")

  expect_identical(agents, agents_md_template(japanese = FALSE))
  expect_match(text, "## Project Map", fixed = TRUE)
  expect_match(text, "`source/`", fixed = TRUE)
  expect_match(text, "`source/initial_YYYYMMDD/`", fixed = TRUE)
  expect_match(text, "`ai_visible_data/`", fixed = TRUE)
  expect_match(text, "`ai_visible_data/initial_YYYYMMDD/`", fixed = TRUE)
  expect_match(text, "`../r_project/ai_hidden_data/`", fixed = TRUE)
  expect_match(text, "`ai_output/`", fixed = TRUE)
  expect_match(text, "`r_output/`", fixed = TRUE)
  expect_match(text, "`qc/`", fixed = TRUE)
  expect_match(text, "`log/`", fixed = TRUE)
  expect_match(text, "`QC_STATUS.md`", fixed = TRUE)
  expect_match(text, "## Statistical Analysis Plan and Analysis Decisions", fixed = TRUE)
  expect_match(text, "`ai_output/SAP.md`", fixed = TRUE)
  expect_match(text, "`ai_output/SAP_DECISIONS.md`", fixed = TRUE)
  expect_match(text, "Codex must not list, open, copy, move, summarize", fixed = TRUE)
  expect_match(text, "## Human Approval", fixed = TRUE)
  expect_match(text, "## Output Language", fixed = TRUE)
  expect_match(text, "generated by Codex should be written in English", fixed = TRUE)

  expect_false(grepl("generated by Codex should be written in Japanese", text, fixed = TRUE))
  expect_false(grepl("`source/initial/`", text, fixed = TRUE))
  expect_false(grepl("`ai_visible_data/initial/`", text, fixed = TRUE))
  expect_false(grepl("Checkpoint QC", text, fixed = TRUE))
  expect_false(grepl("Software Inventory", text, fixed = TRUE))
})

test_that("AGENTS.md records Japanese narrative output language when requested", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "ai_only", japanese = TRUE)

  agents <- readLines(file.path(path, "ai_project", "AGENTS.md"), warn = FALSE)
  text <- paste(agents, collapse = "\n")

  expect_identical(agents, agents_md_template(japanese = TRUE))
  expect_match(text, "## Statistical Analysis Plan and Analysis Decisions", fixed = TRUE)
  expect_match(text, "`ai_output/SAP.md`", fixed = TRUE)
  expect_match(text, "`ai_output/SAP_DECISIONS.md`", fixed = TRUE)
  expect_match(text, "## Output Language", fixed = TRUE)
  expect_match(text, "generated by Codex should be written in Japanese", fixed = TRUE)
  expect_match(text, "R scripts, source code, machine-readable tables", fixed = TRUE)
  expect_false(grepl("generated by Codex should be written in English", text, fixed = TRUE))
})

test_that("japanese must be a single TRUE or FALSE value", {
  path <- tempfile("airsetup-")

  expect_error(airsetup(path, japanese = NA), "japanese.*TRUE or FALSE")
  expect_error(airsetup(path, japanese = c(TRUE, FALSE)), "japanese.*TRUE or FALSE")
  expect_error(airsetup(path, japanese = "yes"), "japanese.*TRUE or FALSE")
})

test_that("QC_STATUS.md is generated as a minimal root status file", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "ai_only")

  qc_status <- readLines(file.path(path, "ai_project", "QC_STATUS.md"), warn = FALSE)

  expect_identical(qc_status, qc_status_template())
  expect_equal(qc_status[1], "# QC_STATUS.md")
  expect_true(any(grepl("No QC items have been registered yet.", qc_status, fixed = TRUE)))
})

test_that("split mode r_project scaffold is minimal and protects hidden data", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "split")

  gitignore <- file.path(path, "r_project", ".gitignore")
  readme <- file.path(path, "r_project", "README_DO_NOT_SHARE_WITH_AI.md")

  expect_true(file.exists(gitignore))
  expect_true(any(readLines(gitignore, warn = FALSE) == "ai_hidden_data/"))

  expect_true(file.exists(readme))
  readme_text <- paste(readLines(readme, warn = FALSE), collapse = "\n")
  expect_match(readme_text, "Do not share this folder with AI", fixed = TRUE)
  expect_match(readme_text, "ai_hidden_data/", fixed = TRUE)
  expect_match(readme_text, "ai_hidden_data/initial_YYYYMMDD/", fixed = TRUE)
  expect_match(readme_text, "../ai_project/ai_output/", fixed = TRUE)
  expect_match(readme_text, "../ai_project/r_output/", fixed = TRUE)

  expect_true(dir.exists(file.path(path, "r_project", "ai_hidden_data")))
  expect_one_dated_initial_dir(file.path(path, "r_project", "ai_hidden_data"))
  expect_false(dir.exists(file.path(path, "r_project", "ai_hidden_data", "initial")))
  expect_false(dir.exists(file.path(path, "r_project", "data")))
  expect_false(dir.exists(file.path(path, "r_project", "programs")))
  expect_false(dir.exists(file.path(path, "r_project", "config")))
  expect_false(dir.exists(file.path(path, "r_project", "outputs")))
})

test_that("aircheck reports missing and found split-mode items", {
  path <- tempfile("airsetup-")
  dir.create(path)

  report <- aircheck(path, mode = "split")
  expect_s3_class(report, "data.frame")
  expect_true(all(c("item", "type", "path", "exists", "required", "message") %in% names(report)))
  expect_true(any(!report$exists))

  airsetup(path, mode = "split")
  report2 <- aircheck(path, mode = "split")

  expect_true(all(report2$exists))
  expect_true("ai_project/source" %in% report2$item)
  expect_true("ai_project/source/initial_YYYYMMDD" %in% report2$item)
  expect_true("ai_project/ai_visible_data" %in% report2$item)
  expect_true("ai_project/ai_visible_data/initial_YYYYMMDD" %in% report2$item)
  expect_true("ai_project/ai_output" %in% report2$item)
  expect_true("ai_project/r_output" %in% report2$item)
  expect_true("ai_project/qc" %in% report2$item)
  expect_true("ai_project/log" %in% report2$item)
  expect_true("ai_project/AGENTS.md" %in% report2$item)
  expect_true("ai_project/QC_STATUS.md" %in% report2$item)
  expect_true("r_project/ai_hidden_data" %in% report2$item)
  expect_true("r_project/ai_hidden_data/initial_YYYYMMDD" %in% report2$item)

  expect_false("ai_project/source/initial" %in% report2$item)
  expect_false("ai_project/ai_visible_data/initial" %in% report2$item)
  expect_false("r_project/ai_hidden_data/initial" %in% report2$item)

  expect_false("ai_project/04_ai_context_package/active/active_task.md" %in% report2$item)
  expect_false("ai_project/05_qc_package/template/checkpoint_definition_template.csv" %in% report2$item)
  expect_false("r_project/programs/run_analysis_template.R" %in% report2$item)
})

test_that("aircheck reports all required ai-only items after creation", {
  path <- tempfile("airsetup-")
  airsetup(path, mode = "ai_only")

  report <- aircheck(path, mode = "ai_only")

  expect_true(all(report$exists))
  expect_true(all(grepl("^ai_project/", report$path)))
  expect_false(any(grepl("^r_project/", report$path)))
  expect_true("ai_project/source" %in% report$item)
  expect_true("ai_project/source/initial_YYYYMMDD" %in% report$item)
  expect_true("ai_project/ai_visible_data" %in% report$item)
  expect_true("ai_project/ai_visible_data/initial_YYYYMMDD" %in% report$item)
  expect_true("ai_project/AGENTS.md" %in% report$item)
  expect_true("ai_project/QC_STATUS.md" %in% report$item)

  expect_false("ai_project/source/initial" %in% report$item)
  expect_false("ai_project/ai_visible_data/initial" %in% report$item)
})

test_that("mode must be split or ai_only", {
  expect_error(airsetup(tempfile("airsetup-"), mode = "other"))
  expect_error(aircheck(tempfile("airsetup-"), mode = "other"))
})
